### ISSUE TITLE
Crear estructura de paquetes

### ISSUE THREAD

**Issue by roger357** [vdiquez/Rbot#1]
# Paquetes
Crear correcta organizacion por paquetes en el proyecto ya que todas las clases estan directamente en el **`src`**.

**Comment by roger357** [comment]
# Primer Commit issue #1
El commit 536966f8d80de13812039e43ada6612cab933a0b apenas es el inicio, aun falta que @vdiquez revise y determine que mas hace falta. Se creo un paquete `unasigned` en el cual coloque clases que no sabia donde reubicar.

**Comment by vdiquez** [comment]
Issues solventado en el commit e8d94f1.
